# Generated by Django 4.1.2 on 2022-11-05 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_options_alter_comment_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post_of_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post'),
        ),
    ]
