# Generated by Django 4.1.2 on 2022-11-09 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_alter_comment_options_remove_comment_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.TextField(verbose_name='Текст комментария')),
                ('created', models.DateTimeField(auto_now=True)),
                ('comment_to_reply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_to_reply', to='blog.comment')),
                ('post_of_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_replied', to='blog.post')),
                ('user_created_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_replied', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='reply_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='blog.replycomment'),
        ),
    ]
