# Generated by Django 4.1.2 on 2022-11-13 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_rename_reply_comment_comment_to_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_to_reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.comment'),
        ),
    ]
