# Generated by Django 4.1.2 on 2022-11-16 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_comment_comment_to_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_to_reply',
            new_name='comm_to_repl',
        ),
        migrations.AlterField(
            model_name='post',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.comment', verbose_name='Комментарий'),
        ),
    ]
